name: Lint

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        run: |
          python -m venv runner
          source runner/bin/activate
          pip install -U pip setuptools wheel black

      - name: Run black to format code
        id: format_code
        run: |
          source runner/bin/activate
          black . --exclude 'runner/'

      - name: Run black format
        id: lint_check
        run: |
          python -m venv runner
          source ./runner/bin/activate
          pip install -U pip setuptools wheel
          pip install black
          black --check . --exclude '/runner/' || echo "needs_formatting" > black_check.txt

      - name: Commit to Git if Black shows differences
        if: ${{ success() && hashFiles('black_check.txt') }}
        run: |
          echo "runner/" >> .gitignore
          git config --local user.email "stephenlightcap94@gmail.com"
          git config --local user.name "sal-git"
          git add --all -- ':!runner/'
          git commit -m "AUTO: black format"

      - name: Push changes
        if: env.needs_formatting == 'true'
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.ACCESS_TOKEN }}
